### ISSUE TITLE
quick peek on properties

### ISSUE THREAD

**Issue by stardiviner** [alphapapa/org-quick-peek#1]
I have a use case to record contact info in properties and drawer, hope `org-quick-peek` can show info in `properties` and `drawer`.

**Comment by alphapapa** [comment]
Hi, thanks for the suggestion.  I'm not sure about this.  Currently we use `org-agenda-get-some-entry-text` to get the entry text, and that function skips drawers.  Of course we could copy that function and adjust it, but it's a fairly large function, so I'm not eager to import its code into this project.

On the other hand, I could import `helm-org-rifle--get-entry-text`, which is much smaller.  That seems doable.

I'll probably push a branch with this change.  If you don't mind testing it, that would be great.  I'll post again here then.

**Comment by stardiviner** [comment]
Ok, I will take a testing. And Can `quick-peek` do image display? Because I come up with an idea to show avatar for org-contacts in org-quick-peek.

**Comment by alphapapa** [comment]
I went ahead and pushed a commit to master that adds this.  Just customize the new option and drawers are displayed.  :)

I'm not sure about image display.  I haven't looked into how Emacs does that.  I *think* it uses text properties, in which case, it might Just Work.

**Comment by alphapapa** [comment]
By the way, curious, how did you find this package?  I haven't published it to MELPA yet so I didn't expect anyone to find it.  I do appreciate it though.  I will probably publish it soon now that someone else has tested it.  :)

**Comment by stardiviner** [comment]
I watched `quick-peek` package.

**Comment by alphapapa** [comment]
Oh cool.  :)
